[album.x]
  mirror_folder="/home/ghibulo/Downloads/hudba"
  folder="MagicSlim"
  state="on"
  order="normal" #normal/shuffle/bigshuffle
  tracks =	[
    ["on", "Magic Slim - Lonely For Your Love.mp3"],
    ["on", "Magic Slim - Chickenheads.mp3"],
    ["on", "Magic Slim- I Need Lovin'.mp3"],
    ["on", "Magic Slim - Bad Boy.mp3"],
    ["on", "Magic Slim- I'm Gonna Get You Babe.mp3"],
    ["on", "05. Girl What You Want Me To Do.mp3"],
    ["on", "Magic Slim Worried Life Blues.mp3"],
    ["on", "Magic Slim - Bad Avenue.mp3"],
    ["on", "Magic Slim - Scufflin'.mp3"],
    ["on", "Magic Slim- 4.59 a.m.mp3"],
    ["on", "Magic Slim- Key to Your Door.mp3"],
    ["on", "Magic Slim - Matchbox Blues.mp3"],
    ["on", "Magic Slim I'm A Man.mp3"],
    ["on", "Magic Slim - Please Don't Dog Me.mp3"],
    ["on", "Magic Slim- Hard Luck Blues.mp3"],
    ["on", "Magic Slim - Mustang Sally.mp3"],
    ["on", "Magic Slim.Son Seals & The Chicago Fire Band - The Sun Is Shining.mp3"],
    ["on", "06. Hard Luck Blues.mp3"],
    ["on", "Magic Slim - Young Man's Blues.mp3"],
    ["on", "Magic Slim - I Can't Hold Out.mp3"],
    ["on", "Magic Slim- Loving You Is The Best Thing That Ever Happened To Me.mp3"],
    ["on", "Magic Slim - Cold Women With Warm Hearts.mp3"],
    ["on", "Magic Slim - What Is It That You Got.mp3"],
    ["on", "Magic Slim- Black Tornado.mp3"],
    ["on", "Magic Slim & The Teardrops - I Can't Hold Out.mp3"],
    ["on", "Magic Slim - What's Wrong.mp3"],
    ["on", "Magic Slim- How Much More Long.mp3"],
    ["on", "Magic Slim - Older Woman.mp3"],
    ["on", "Magic Slim Walking Whole Night Long.mp3"],
    ["on", "Magic Slim - Lookin' For A Lover.mp3"],
    ["on", "Magic Slim- Lonely Man.mp3"],
    ["on", "Magic Slim.Lonnie Brooks - Trading Post.mp3"],
    ["on", "Magic Slim- I Got Money.mp3"],
    ["on", "Magic Slim - Before you accuse me.mp3"],
    ["on", "Magic Slim - Down in Virginia.mp3"],
    ["on", "Magic Slim - A'int That Nice.mp3"],
    ["on", "Magic Slim - Hard To Handle.mp3"],
    ["on", "Magic Slim - She Moves Me.mp3"],
    ["on", "Magic Slim Mustang Sally.mp3"],
    ["on", "08. Champagne and Reefer.mp3"],
    ["on", "Magic Slim - Spider In My Stew.mp3"],
    ["on", "Magic Slim - The Moon Is Full.mp3"],
    ["on", "Magic Slim - Magic Boogie.mp3"],
    ["on", "Magic Slim - I'm Gonna Send You Back To Georgia.mp3"],
    ["on", "Magic Slim- Goin' to MIssissippi.mp3"],
    ["on", "Magic Slim - What's wrong.mp3"],
    ["on", "Magic Slim - It's All Right.mp3"],
    ["on", "Magic Slim - Little Red Rooster.mp3"],
    ["on", "Magic Slim- Chapel Hill Boogie.mp3"],
    ["on", "Magic Slim- Love My Baby.mp3"],
    ["on", "Magic Slim - Slim's Hideaway.mp3"],
    ["on", "Magic Slim- Get Your Business Straight.mp3"],
    ["on", "Magic Slim.Lonnie Brooks - In The Dark.mp3"],
    ["on", "Magic Slim If It's Too Late  (Nick Holt Vc).mp3"],
    ["on", "Magic Slim - Before You Accuse Me.mp3"],
    ["on", "03. I Got Money.mp3"],
    ["on", "Magic Slim - Get your business straight.mp3"],
    ["on", "Magic Slim - Full Load Boogie.mp3"],
    ["on", "Magic Slim - Goin' To Mississippi.mp3"],
    ["on", "test.m3u"],
    ["on", "02. Someone Else Is Steppin' In.mp3"],
    ["on", "Magic Slim- Room 109.mp3"],
    ["on", "Magic Slim.Son Seals & The Chicago Fire Band - Look Now, Baby.mp3"],
    ["on", "Magic Slim- Shake It.mp3"],
    ["on", "Magic Slim- Goin'To Mississippi.mp3"],
    ["on", "Magic Slim - Country Boy.mp3"],
    ["on", "Magic Slim - So Easy To Love You.mp3"],
    ["on", "Magic Slim- I Can't Trust My Woman.mp3"],
    ["on", "Magic Slim - Pretty Girls Everywhere.mp3"],
    ["on", "Magic Slim- Champagne and Reefer.mp3"],
    ["on", "Magic Slim - Just Before You Go.mp3"],
    ["on", "Magic Slim - Come On In This House.mp3"],
    ["on", "Magic Slim - Please don't dog me.mp3"],
    ["on", "Magic Slim- Going Down The Road Feeling Bad.mp3"],
    ["on", "Magic Slim - I Need Lovin'.mp3"],
    ["on", "Magic Slim - Shake It.mp3"],
    ["on", "Magic Slim - Someone Else Is Steppin' In.mp3"],
    ["on", "Magic Slim - Lump on Your Stump.mp3"],
    ["on", "Magic Slim - Let Me Love You.mp3"],
    ["on", "Magic Slim.Son Seals & The Chicago Fire Band - I Can't Hold Out.mp3"],
    ["on", "Magic Slim - Lonesome Trouble.mp3"],
    ["on", "Magic Slim - Crazy Woman.mp3"],
    ["on", "Magic Slim - Gambler.mp3"],
    ["on", "Magic Slim & The Teardrops - Loving You.mp3"],
    ["on", "Magic Slim - Can't Get No Grindin'.mp3"],
    ["on", "Magic Slim - I Don't Believe You Baby.mp3"],
    ["on", "Magic Slim- I Ain't Lookin' for No Love.mp3"],
    ["on", "Magic Slim - It's Alright.mp3"],
    ["on", "Magic Slim- Down In Virginia.mp3"],
    ["on", "Magic Slim - Please Don't Waste My time.mp3"],
    ["on", "Magic Slim - Jealous Man.mp3"],
    ["on", "01. Bad Boy.mp3"],
    ["on", "Magic Slim- Gravel Road.mp3"],
    ["on", "Magic Slim- I'm Good.mp3"],
    ["on", "Magic Slim - How many more years.mp3"],
    ["on", "Magic Slim - Country Girl.mp3"],
    ["on", "Magic Slim- Further On Up The Road.mp3"],
    ["on", "Magic Slim - I'm A Bluesman.mp3"],
    ["on", "Magic Slim- Iwant To See You In The Evening.mp3"],
    ["on", "Magic Slim- Gambling Blues.mp3"],
    ["on", "Magic Slim & The Teardrops - If You Got To Love Somebody.mp3"],
    ["on", "Magic Slim - Mind Your Own Business.mp3"],
    ["on", "09. How Much More Long.mp3"],
    ["on", "Magic Slim- Please Don't Dog Me.mp3"],
    ["on", "Magic Slim- Scufflin'.mp3"],
    ["on", "Magic Slim - Hole In The Wall.mp3"],
    ["on", "12. _  Country Joyride.mp3"],
    ["on", "Magic Slim- I'm Not The Same Person.mp3"],
    ["on", "Magic Slim.Son Seals & The Chicago Fire Band - Every Day I Have The Blues.mp3"],
    ["on", "Magic Slim - You've Got Bad Intentions.mp3"],
    ["on", "Magic Slim - Country Joyride.mp3"],
    ["on", "Magic Slim- Meet Me In My Own Hometown.mp3"],
    ["on", "Magic Slim Breaking Up Somebody's Home.mp3"],
    ["on", "Magic Slim- Bad Luck Is Fallin'.mp3"],
    ["on", "Magic Slim- The Man You Need.mp3"],
    ["on", "Magic Slim - The Man You Need.mp3"],
    ["on", "Magic Slim- Gonna Move To Kansas City.mp3"],
    ["on", "Magic Slim .Lonnie Brooks - Bewitched.mp3"],
    ["on", "Magic Slim - Mama Talk To Your Daughter.mp3"],
    ["on", "Magic Slim.Lonnie Brooks - Two Headed Man.mp3"],
    ["on", "Magic Slim .Lonnie Brooks - I Want All My Money Back.mp3"],
    ["on", "Magic Slim - Cryin' Won't Let You Stay.mp3"],
    ["on", "Magic Slim - Think.mp3"],
    ["on", "Magic Slim - Bad Luck.mp3"],
    ["on", "Magic Slim- House Cat Blues.mp3"],
    ["on", "Magic Slim.Son Seals & The Chicago Fire Band - Don't You Lie To Me.mp3"],
    ["on", "Magic Slim- Do You Mean It.mp3"],
    ["on", "Magic Slim - Sunrise Blues.mp3"],
    ["on", "Magic Slim - Playin With My Mind.mp3"],
    ["on", "Magic Slim - Crosseyed Cat.mp3"],
    ["on", "Magic Slim - Snakebite.mp3"],
    ["on", "Magic Slim - I Started Loving You Again.mp3"],
    ["on", "Magic Slim - Black Tornado.mp3"],
    ["on", "Magic Slim- Girl What You Want Me To Do.mp3"],
    ["on", "Magic Slim- Shame.mp3"],
    ["on", "04. Sunrise Blues.mp3"],
    ["on", "Magic Slim- Playin' with my mind.mp3"],
    ["on", "Magic Slim - Give Me Back My Wig.mp3"],
    ["on", "Magic Slim- You Got To Pay.mp3"],
    ["on", "Magic Slim - Carla.mp3"],
    ["on", "Magic Slim - Evil Woman Blues.mp3"],
    ["on", "Magic Slim - Still A Fool.mp3"],
    ["on", "Magic Slim - Still a Fool.mp3"],
    ["on", "Magic Slim.Lonnie Brooks - Eyeballing.mp3"],
    ["on", "Magic Slim- I'm A Bluesman.mp3"],
    ["on", "Magic Slim- Built For Comfort.mp3"],
    ["on", "Magic Slim- Mama Talk To Your Daughter.mp3"],
    ["on", "Magic Slim - Come On Pretty Baby.mp3"],
    ["on", "Magic Slim - I'm A Stranger.mp3"],
    ["on", "Magic Slim - Part Time Love.mp3"],
    ["on", "Magic Slim You Can't Lose What You Ain't Never Had.mp3"],
    ["on", "Magic Slim - Get Your Business Straight.mp3"],
    ["on", "Magic Slim - Love Like I Wanna.mp3"],
    ["on", "Magic Slim - Mary Lee.mp3"],
    ["on", "11. Older Woman.mp3"],
    ["on", "Magic Slim In The Heart Of The Blues.mp3"],
    ["on", "Magic Slim.Son Seals & The Chicago Fire Band - Come Back To Me.mp3"],
    ["on", "Magic Slim- Cummins Prison Farm.mp3"],
    ["on", "Magic Slim - Treat Me The Way You Do.mp3"],
    ["on", "07. Gambling Blues.mp3"],
    ["on", "Magic Slim- Wake Me Up Early.mp3"],
    ["on", "10. Matchbox Blues.mp3"],
    ["on", "Magic SlimDon't Tell Me About Your Trouble.mp3"],
    ["on", "Magic Slim & The Teardrops - Look On Yonder Wall.mp3"],
    ["on", "Magic Slim- Sunny Road Blues.mp3"],
    ["on", "Magic Slim- Mind your own business.mp3"],
    ["on", "Magic Slim- Prisoner Of Love.mp3"],
    ["on", "Magic Slim - I Got Money.mp3"]
  ]
