[album.x]
  mirror_folder="/home/ghibulo/Downloads/hudba"
  folder="zp2"
  state="on"
  order="normal" #normal/shuffle/bigshuffle
  tracks =	[
    ["on", "03_Male nocni slunce (128).mp3"],
    ["on", "02_Kletba oceanu (128).mp3"],
    ["on", "05_Skotsko na rovniku (128).mp3"],
    ["on", "01_Clovek s tvari opice (128).mp3"],
    ["on", "10_Sedm stop zeme (128).mp3"],
    ["on", "09_Konec cisarske flotily (128).mp3"],
    ["on", "07_Pet roku hladu (128).mp3"],
    ["on", "08_Bila proti cerne (128).mp3"],
    ["on", "06_Podzemni jablka (128).mp3"],
    ["on", "11_Bledy jezdec, bledy kun (128).mp3"],
    ["on", "04_Gentlemani cizi dopisy nectou (128).mp3"]
  ]
