mount_folder = "/media/ghibulo/G118S"
mirror_folder = "/home/ghibulo/programovani/dart/mirrorFolder"

[album]

[album.1]
mirror_folder = "/home/ghibulo/Downloads/hudba"
folder = "zp1"
state = "on"
order = "normal" #normal/shuffle/bigshuffle
tracks =	[
    ["on", "04_Povesen za krk.mp3"],
    ["off", "03_Pompeje dvaceteho stoleti.mp3"],
    ["off", "01_Prolog.mp3"],
    ["off", "05_Variola vera.mp3"],
    ["off", "07_Vanocni klid mezi zakopy.mp3"],
    ["off", "cti-mne.txt"],
    ["off", "06_Krvavy snih.mp3"],
    ["off", "08_Epilog.mp3"],
    ["off", "02_Blucher priplouva.mp3"]
]


[album.2]
mirror_folder = "/home/ghibulo/Downloads/hudba"
folder = "zp2"
state = "off"
order = "shuffle" #normal/shuffle/bigshuffle
tracks =	[
    ["on", "03_Male nocni slunce (128).mp3"],
    ["on", "02_Kletba oceanu (128).mp3"],
    ["on", "05_Skotsko na rovniku (128).mp3"],
    ["on", "01_Clovek s tvari opice (128).mp3"],
    ["on", "10_Sedm stop zeme (128).mp3"],
    ["on", "09_Konec cisarske flotily (128).mp3"],
    ["on", "07_Pet roku hladu (128).mp3"],
    ["on", "08_Bila proti cerne (128).mp3"],
    ["on", "06_Podzemni jablka (128).mp3"],
    ["on", "11_Bledy jezdec, bledy kun (128).mp3"],
    ["on", "04_Gentlemani cizi dopisy nectou (128).mp3"]
]

[album.x]
mirror_folder = "/home/ghibulo/Downloads/hudba"
folder = "flac"
state = "on"
order = "bigshuffle" #normal/shuffle/bigshuffle
tracks = [
    ["on", "01. Bad Boy.flac"],
    ["on", "06. Hard Luck Blues.flac"],
    ["on", "03. I Got Money.flac"],
    ["on", "07. Gambling Blues.flac"],
    ["on", "10. Matchbox Blues.flac"],
    ["on", "08. Champagne and Reefer.flac"],
    ["on", "11. Older Woman.flac"],
    ["on", "04. Sunrise Blues.flac"],
    ["on", "05. Girl What You Want Me To Do.flac"],
    ["on", "12. CountryJoyride.flac"],
    ["on", "02. Someone Else Is Steppin' In.flac"],
    ["on", "09. How Much More Long.flac"]
]
