mount_folder="/home/ghibulo/programovani/dart/mountFolder"
mirror_folder="/home/ghibulo/programovani/dart/mirrorFolder"

[album]
    [album.1]
      mirror_folder="/home/ghibulo/Downloads/hudba"
      folder="flac"
      state="on"
      order="shuffle" #normal/shuffle/bigshuffle
      tracks =	[
        ["off", "01. Bad Boy.flac"],
        ["off", "06. Hard Luck Blues.flac"],
        ["on", "03. I Got Money.flac"],
        ["on", "12. _  Country Joyride.flac"]
      ]

    [album.2]
      mirror_folder="/home/ghibulo/Downloads/hudba"
      folder="zp1"
      state="off"
      order="normal" #normal/shuffle/bigshuffle
      tracks =	[
        ["on", "04_Povesen za krk.mp3"],
        ["off", "03_Pompeje dvaceteho stoleti.mp3"],
        ["off", "02_Blucher priplouva.mp3"]
      ]


    [album.3]
      mirror_folder="/home/ghibulo/Downloads/hudba"
      folder="zp2"
      state="on"
      order="shuffle" #normal/shuffle/bigshuffle
      tracks =	[
        ["on", "03_Male nocni slunce (128).mp3"],
        ["off", "02_Kletba oceanu (128).mp3"],
        ["on", "04_Gentlemani cizi dopisy nectou (128).mp3"]
      ]

    [album.5]
      mirror_folder="/home/ghibulo/Downloads/hudba"
      folder="MagicSlim"
      state="on"
      order="shuffle" #normal/shuffle/bigshuffle
      tracks =	[
        ["on", "Magic Slim - Lonely For Your Love.mp3"],
        ["on", "Magic Slim - Chickenheads.mp3"],
        ["on", "Magic Slim - I Got Money.mp3"]
      ]
