source_config = "/home/ghibulo/IdeaProjects/AudioPlayerManager/sfsconfig.toml"
mount_folder = "/home/ghibulo/programovani/dart/mountFolder"


[album1]
order = "normal" #normal/shuffle/bigshuffle
tracks =	[
    "06_Krvavy snih.mp3",
    "02_Blucher priplouva.mp3"
]


[album2]
order = "shuffle" #normal/shuffle/bigshuffle
tracks =	[
    "03_Male nocni slunce (128).mp3",
    "09_Konec cisarske flotily (128).mp3",
    "04_Gentlemani cizi dopisy nectou (128).mp3"
]

[albumx]
order = "bigshuffle" #normal/shuffle/bigshuffle
tracks = [
    "01. Bad Boy.flac",
    "06. Hard Luck Blues.flac",
    "03. I Got Money.flac",
    "07. Gambling Blues.flac"
]
