source_config = "/home/ghibulo/IdeaProjects/AudioPlayerManager/sfsconfig.toml"
mount_folder = "/home/ghibulo/programovani/dart/mountFolder"

[album1]
mirror_folder = "./Cteni/beletrieCj"
folder = "zp1"
order = "bigshuffle" #normal/shuffle/bigshuffle
tracks =	[
    "04_Povesen za krk.mp3",
    "03_Pompeje dvaceteho stoleti.mp3",
    "01_Prolog.mp3",
    "05_Variola vera.mp3",
    "07_Vanocni klid mezi zakopy.mp3",
    "cti-mne.txt",
    "06_Krvavy snih.mp3",
    "08_Epilog.mp3",
    "02_Blucher priplouva.mp3"
]

[album2]
mirror_folder = "./Cteni/beletrieCj"
folder = "zp2"
order = "bigshuffle" #normal/shuffle/bigshuffle
tracks =	[
    "03_Male nocni slunce (128).mp3",
    "02_Kletba oceanu (128).mp3",
    "05_Skotsko na rovniku (128).mp3",
    "10_Sedm stop zeme (128).mp3",
    "09_Konec cisarske flotily (128).mp3",
    "07_Pet roku hladu (128).mp3",
    "08_Bila proti cerne (128).mp3",
    "06_Podzemni jablka (128).mp3",
    "04_Gentlemani cizi dopisy nectou (128).mp3"
]

[albumx]
mirror_folder = "./Hudba/MagicSlim"
folder = "flac"
order = "bigshuffle" #normal/shuffle/bigshuffle
tracks = [
    "01. Bad Boy.flac",
    "06. Hard Luck Blues.flac",
    "03. I Got Money.flac",
    "07. Gambling Blues.flac",
    "10. Matchbox Blues.flac",
    "08. Champagne and Reefer.flac",
    "11. Older Woman.flac",
    "04. Sunrise Blues.flac",
    "05. Girl What You Want Me To Do.flac",
    "12. CountryJoyride.flac",
    "02. Someone Else Is Steppin' In.flac",
    "09. How Much More Long.flac"
]

